# Generated by Django 3.0 on 2022-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverNameAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('advice', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='RiverAdvice',
        ),
        migrations.DeleteModel(
            name='RiverName',
        ),
    ]
