# Generated by Django 3.0 on 2022-01-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0004_alter_rivernameadvice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rivernameadvice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
